
#  POST  http://localhost:8080/room/add-room  HTTP/1.1 
#  Content-Type: application/json
#  Accept-Language: en-us

#  {
#    "ClassNumber":3
#  }
 ###

POST  http://localhost:8080/course/add-course HTTP/1.1
Content-Type: application/json
Accept-Language: en-us

 {
    "CourseName":"Its",
    "StartingDate": "2023-05-01",
    "EndDate": "2024-04-01",
    "MinimumPassingScore" :11,
     "MaximumStudents": 30,
     "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXclfj6LB1o937n72XdeIMJ6KN7oABP1e8uCbBdwORD3PmErDbQ34pDQ1Lt5LjFNceOUM&usqp=CAU",
    "IsReady":false
 }

 

###



 POST  http://localhost:8080/test/add-test HTTP/1.1 
 Content-Type: application/json
 Accept-Language: en-us


 {
   "TestName":"OOP Test"
 }