
 GET  http://localhost:8080/course/:courseId HTTP/1.1 
 Content-Type: application/json
Accept-Language: en-us

 {
    "ID":"e0cf2c14-4516-495f-ba2e-ebad798a8d95"
 }






# POST http://localhost:8080/course/course_name HTTP/1.1
# Content-Type: application/json
# Accept-Language: en-us


# {
#    "Course_name" :"david",
  

# }